Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "file", source: "test.txt", destination: "/home/vagrant/test.txt"
  config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update -y
     sudo apt-get install -y python3 python3-pip libpq-dev python-setuptools
	 pip3 install psycopg2 django
  SHELL
end
